app/simple_switch: fix commit e5e4b844250d36788f9b1bf71cfd36a6e14d5315 regression
Traceback (most recent call last):
  File "bin/ryu-manager", line 71, in <module>
    main()
  File "bin/ryu-manager", line 53, in main
    app_mgr.instantiate_apps(**contexts)
  File "/Users/fujita/git/ryu/ryu/base/app_manager.py", line 102, in instantiate_apps
    app = cls(*args, **kwargs)
  File "/Users/fujita/git/ryu/ryu/app/simple_switch.py", line 44, in __init__
    self.mac2port = kwargs['mac2port']
KeyError: 'mac2port'

Signed-off-by: FUJITA Tomonori <fujita.tomonori@lab.ntt.co.jp>