packet lib: fix icmpv6.nd_s.parser() and support NDP option type
This patch fixes parser error if there is no NDP option, and support
the class to handle the NDP option.

I have implemented only the option type = 1 and 2. We also need to
implement other type, but this is enough in mininet for now.

> Traceback (most recent call last):
> (...)
>   File "/usr/local/lib/python2.7/dist-packages/ryu-1.6-py2.7.egg/ryu/lib/packet/icmpv6.py", line 87, in parser
>     msg.data = cls_.parser(buf, offset)
>   File "/usr/local/lib/python2.7/dist-packages/ryu-1.6-py2.7.egg/ryu/lib/packet/icmpv6.py", line 134, in parser
>     buf, offset)
> error: unpack_from requires a buffer of at least 28 bytes

Signed-off-by: HIYAMA Manabu <hiyama.manabu@po.ntts.co.jp>
Signed-off-by: FUJITA Tomonori <fujita.tomonori@lab.ntt.co.jp>