ofctl_rest: fix mod_meter_entry in OpenFlow1.0/1.2
mod_meter_entry causes the following error when the protocol version is 1.0 or 1.2.

  AttributeError: 'module' object has no attribute 'OFPMC_ADD'

this patch fixes this problem.

Signed-off-by: Yuichi Ito <ito.yuichi0@gmail.com>
Signed-off-by: FUJITA Tomonori <fujita.tomonori@lab.ntt.co.jp>