six.add_metaclass requires six>=1.4.0
python-six package from Ubuntu 12.04 LTS remains version 1.1.0,
which prevents ryu-manager from being started and raises exception
"AttributeError: 'module' object has no attribute 'add_metaclass'".

Signed-off-by: Wei-Li Tang <alextwl@xinguard.com>
Signed-off-by: FUJITA Tomonori <fujita.tomonori@lab.ntt.co.jp>